import type { Artifacts, DatasetItem, RuleCheck, SkillAnalysis } from "./types";

const DAY = new Date().toISOString().slice(0, 10);

/* ------------------------------------------------------------------ */
/* public entry                                                        */
/* ------------------------------------------------------------------ */

export function generateArtifacts(a: SkillAnalysis): Artifacts {
  const rules = buildRuleChecks(a);
  const items = buildDatasetItems(a);
  const datasetName = `${a.skillName}-eval`;

  return {
    datasetSchema: JSON.stringify(buildDatasetSchema(a, datasetName), null, 2),
    datasetItems: JSON.stringify(items, null, 2),
    ruleScorersPy: emitRuleScorersPy(a, rules),
    ruleChecksJson: JSON.stringify(rules, null, 2),
    llmJudgePrompt: emitJudgePrompt(a),
    llmJudgePy: emitJudgePy(a),
    langfuseConfigPy: emitLangfuseConfigPy(a, datasetName, items.length),
    envExample: emitEnvExample(),
    packReadme: emitPackReadme(a, rules, items),
  };
}

/* ------------------------------------------------------------------ */
/* dataset                                                             */
/* ------------------------------------------------------------------ */

function buildDatasetSchema(a: SkillAnalysis, datasetName: string) {
  return {
    name: datasetName,
    description: `Evaluation dataset for the "${a.skillName}" skill. Generated by SkillFuse on ${DAY}.`,
    metadata: {
      skill: a.skillName,
      generator: "skillfuse",
      generator_version: "0.1.0",
      task_types: inferTaskTypes(a),
      formats: a.formats,
    },
    item_schema: {
      input: {
        task: "string — the user request that should trigger the skill",
        context: "object — optional attachments / constraints for the run",
      },
      expectedOutput: {
        must_include: "string[] — elements a passing output must contain",
        must_not_include: "string[] — elements a passing output must not contain",
        format: "string — expected output format",
        reference_outline: "string[] — expected section structure (when applicable)",
        notes: "string — grading notes for this item",
      },
      metadata: {
        source: "skill-body | skill-example | constraint-adversarial | llm-augmented",
        section: "string — originating section of the skill",
        tags: "string[]",
        difficulty: "basic | intermediate | edge",
      },
    },
    usage: [
      "python: langfuse.create_dataset(name=..., description=..., metadata=...)",
      "then langfuse.create_dataset_item(dataset_name=..., input=..., expected_output=..., metadata=...)",
    ],
  };
}

function buildDatasetItems(a: SkillAnalysis): DatasetItem[] {
  const items: DatasetItem[] = [];
  const skillRef = a.description ? a.description.slice(0, 160) : a.displayName;

  // 1. happy-path items from trigger keywords / steps
  const triggers = a.triggerKeywords.length > 0 ? a.triggerKeywords : [a.displayName];
  for (const t of triggers.slice(0, 3)) {
    items.push({
      input: {
        task: synthesizeTask(t, a),
        context: {},
      },
      expectedOutput: {
        must_include: mustInclude(a),
        must_not_include: mustNotInclude(a),
        format: a.formats[0] || "markdown",
        reference_outline: a.outputSections.length > 0 ? a.outputSections : a.steps.slice(0, 5),
        notes: `Happy-path item derived from trigger "${t}". Fill in a concrete reference answer before relying on exact-match scoring.`,
      },
      metadata: {
        source: "skill-body",
        section: "description",
        tags: ["happy-path", a.skillName],
        difficulty: "basic",
      },
    });
  }

  // 2. example-based items from code blocks in the skill
  for (const ex of a.examples.slice(0, 3)) {
    items.push({
      input: {
        task: `Produce the output demonstrated in the skill example${ex.caption ? ` (${ex.caption})` : ""} for the skill "${a.skillName}".`,
        context: { example_language: ex.lang },
      },
      expectedOutput: {
        must_include: ex.code
          .split("\n")
          .map((l) => l.trim())
          .filter((l) => l.length > 10)
          .slice(0, 5),
        format: ex.lang || a.formats[0] || "text",
        reference: ex.code.slice(0, 2000),
        notes: "Reference taken verbatim from a code block inside the skill body.",
      },
      metadata: {
        source: "skill-example",
        section: ex.caption,
        tags: ["example", a.skillName],
        difficulty: "intermediate",
      },
    });
  }

  // 3. constraint-adversarial items
  for (const c of a.constraints.slice(0, 2)) {
    items.push({
      input: {
        task: `${synthesizeTask(triggers[0], a)} (This run specifically probes the constraint: "${c}")`,
        context: { probe_constraint: c },
      },
      expectedOutput: {
        must_not_include: mustNotInclude(a),
        format: a.formats[0] || "markdown",
        notes: `Adversarial item: a passing answer must respect the hard rule "${c}".`,
      },
      metadata: {
        source: "constraint-adversarial",
        section: "constraints",
        tags: ["constraint", "edge-case", a.skillName],
        difficulty: "edge",
      },
    });
  }

  if (items.length === 0) {
    items.push({
      input: { task: `Use the "${a.skillName}" skill: ${skillRef}`, context: {} },
      expectedOutput: {
        must_include: mustInclude(a),
        format: a.formats[0] || "markdown",
        notes: "Fallback item — no triggers, examples or constraints were detected in the skill.",
      },
      metadata: { source: "skill-body", section: "", tags: [a.skillName], difficulty: "basic" },
    });
  }

  return items.slice(0, 8);
}

function synthesizeTask(trigger: string, a: SkillAnalysis): string {
  const inputHint = a.inputs.length > 0 ? `, given ${a.inputs[0]}` : "";
  return `A user asks${inputHint}: "${trigger}". Execute the "${a.skillName}" skill end-to-end and produce its expected deliverable.`;
}

function mustInclude(a: SkillAnalysis): string[] {
  const out: string[] = [];
  if (a.outputFields.length > 0) out.push(...a.outputFields.slice(0, 4));
  else if (a.outputSections.length > 0) out.push(...a.outputSections.slice(0, 4));
  else if (a.steps.length > 0) out.push(...a.steps.slice(0, 3).map((s) => s.slice(0, 60)));
  if (a.formats.includes("table")) out.push("a rendered table");
  if (a.formats.includes("code")) out.push("a code block");
  return out;
}

function mustNotInclude(a: SkillAnalysis): string[] {
  const out: string[] = [];
  for (const c of a.constraints) {
    const quoted = [...c.matchAll(/["'“”`]([^"'“”`]{2,60})["'“”`]/g)].map((m) => m[1]);
    if (/never|禁止|不得|不要|avoid|forbidden/i.test(c)) out.push(...quoted.slice(0, 2));
  }
  return [...new Set(out)].slice(0, 6);
}

function inferTaskTypes(a: SkillAnalysis): string[] {
  const t: string[] = [];
  if (a.formats.some((f) => ["pptx", "docx", "xlsx", "pdf", "html", "image"].includes(f))) t.push("artifact-generation");
  if (a.formats.includes("code")) t.push("code-generation");
  if (a.formats.some((f) => ["report", "markdown", "chart"].includes(f))) t.push("writing-and-analysis");
  if (a.tools.length > 3) t.push("tool-use");
  return t.length > 0 ? t : ["general"];
}

/* ------------------------------------------------------------------ */
/* rule checks                                                         */
/* ------------------------------------------------------------------ */

export function buildRuleChecks(a: SkillAnalysis): RuleCheck[] {
  const rules: RuleCheck[] = [
    {
      id: "non_empty",
      name: "Output is non-empty",
      description: "The model produced a substantive answer.",
      kind: "non_empty",
      params: {},
      weight: 1,
      source: "universal",
    },
    {
      id: "min_length",
      name: "Minimum length",
      description: "The answer is long enough to plausibly complete the skill.",
      kind: "min_length",
      params: { min: a.formats.some((f) => ["report", "pptx", "docx"].includes(f)) ? 400 : 120 },
      weight: 1,
      source: "format heuristic",
    },
  ];

  if (a.formats.includes("json")) {
    rules.push({
      id: "valid_json",
      name: "Valid JSON",
      description: "Output parses as JSON (the skill declares JSON output).",
      kind: "valid_json",
      params: {},
      weight: 2,
      source: "declared format: json",
    });
  }
  if (a.formats.includes("markdown") || a.formats.includes("report")) {
    rules.push({
      id: "has_heading",
      name: "Has heading structure",
      description: "Markdown output contains at least one heading.",
      kind: "has_heading",
      params: {},
      weight: 1,
      source: "declared format: markdown/report",
    });
  }
  if (a.formats.includes("table")) {
    rules.push({
      id: "has_table",
      name: "Contains a table",
      description: "Output contains a markdown table.",
      kind: "has_table",
      params: {},
      weight: 1,
      source: "declared format: table",
    });
  }
  if (a.formats.includes("code")) {
    rules.push({
      id: "has_code_block",
      name: "Contains a code block",
      description: "Output contains at least one fenced code block.",
      kind: "has_code_block",
      params: {},
      weight: 2,
      source: "declared format: code",
    });
  }

  // banned terms from never-constraints
  const banned = mustNotInclude(a);
  if (banned.length > 0) {
    rules.push({
      id: "no_banned_terms",
      name: "Respects hard constraints",
      description: `Output must not contain: ${banned.join(", ")}.`,
      kind: "not_contains",
      params: { terms: banned },
      weight: 3,
      source: "skill constraints (never/禁止)",
    });
  }

  // emoji ban is common in skills
  if (a.constraints.some((c) => /emoji/i.test(c) && /never|禁止|不得|不要|avoid|no /i.test(c))) {
    rules.push({
      id: "no_emoji",
      name: "No emoji",
      description: "The skill forbids emoji in the deliverable.",
      kind: "no_emoji",
      params: {},
      weight: 2,
      source: "skill constraint: no emoji",
    });
  }

  // required sections — prefer concrete output fields over section headings
  const required = (a.outputFields.length > 0 ? a.outputFields : a.outputSections).slice(0, 5);
  if (required.length > 0) {
    rules.push({
      id: "required_sections",
      name: "Required sections present",
      description: `Output should cover: ${required.join(" / ")}.`,
      kind: "contains_any",
      params: { terms: required, min_match: Math.max(1, Math.ceil(required.length / 2)) },
      weight: 2,
      source: "skill output-structure section",
    });
  }

  return rules;
}

/* ------------------------------------------------------------------ */
/* python emitters                                                     */
/* ------------------------------------------------------------------ */

function emitRuleScorersPy(a: SkillAnalysis, rules: RuleCheck[]): string {
  return `"""Deterministic rule scorers for the "${a.skillName}" skill.

Generated by SkillFuse on ${DAY}. No external dependencies — works with or
without the Langfuse SDK. Each scorer returns (name, value, comment) where
value is 1.0 (pass) or 0.0 (fail); use \`run_all\` for the weighted aggregate.
"""

import json
import re

RULES = json.loads(r'''${JSON.stringify(rules).replace(/'/g, "\\u0027")}''')

WEIGHT_TOTAL = sum(r.get("weight", 1) for r in RULES) or 1


def _check(rule, output: str) -> tuple[bool, str]:
    kind = rule["kind"]
    p = rule.get("params", {})
    text = output or ""

    if kind == "non_empty":
        ok = len(text.strip()) > 0
        return ok, "output is non-empty" if ok else "output is empty"
    if kind == "min_length":
        n = p.get("min", 100)
        ok = len(text.strip()) >= n
        return ok, f"length {len(text.strip())} >= {n}" if ok else f"too short: {len(text.strip())} chars (< {n})"
    if kind == "max_length":
        n = p.get("max", 20000)
        ok = len(text) <= n
        return ok, f"length {len(text)} <= {n}" if ok else f"too long: {len(text)} chars (> {n})"
    if kind == "valid_json":
        candidate = text.strip()
        m = re.search(r"\`\`\`(?:json)?\\s*([\\s\\S]*?)\`\`\`", candidate)
        if m:
            candidate = m.group(1).strip()
        try:
            json.loads(candidate)
            return True, "output parses as JSON"
        except Exception as exc:
            return False, f"invalid JSON: {exc}"
    if kind == "has_heading":
        ok = re.search(r"^#{1,6}\\s+\\S", text, re.M) is not None
        return ok, "found markdown heading" if ok else "no markdown heading found"
    if kind == "has_table":
        ok = re.search(r"^\\s*\\|.+\\|\\s*$", text, re.M) is not None
        return ok, "found markdown table" if ok else "no markdown table found"
    if kind == "has_code_block":
        ok = "\`\`\`" in text
        return ok, "found fenced code block" if ok else "no fenced code block found"
    if kind == "no_emoji":
        m = re.search("[\\U0001F300-\\U0001FAFF\\u2600-\\u27BF\\uFE0F\\u200D]", text)
        return m is None, "no emoji found" if m is None else f"emoji found: {m.group(0)}"
    if kind == "contains_any":
        terms = p.get("terms", [])
        flags = p.get("flags", "")
        if "regex" in p:
            ok = re.search(p["regex"], text, re.U if "u" in flags else 0) is None
            return ok, "pattern absent" if ok else f"forbidden pattern found: {p['regex']}"
        hits = [t for t in terms if t.lower() in text.lower()]
        need = p.get("min_match", len(terms))
        ok = len(hits) >= need
        return ok, f"matched {len(hits)}/{need}: {hits}"
    if kind == "contains_all":
        terms = p.get("terms", [])
        missing = [t for t in terms if t.lower() not in text.lower()]
        return not missing, "all terms present" if not missing else f"missing: {missing}"
    if kind == "not_contains":
        if "regex" in p:
            m = re.search(p["regex"], text, re.U if "u" in p.get("flags", "") else 0)
            return m is None, "forbidden pattern absent" if m is None else f"found forbidden pattern: {m.group(0)!r}"
        terms = p.get("terms", [])
        hits = [t for t in terms if t.lower() in text.lower()]
        return not hits, "no banned terms found" if not hits else f"banned terms found: {hits}"
    return True, f"unknown rule kind {kind!r} (skipped)"


def score(output: str) -> list[tuple[str, float, str]]:
    """Run every rule; returns a list of (rule_id, value, comment)."""
    results = []
    for rule in RULES:
        ok, comment = _check(rule, output)
        results.append((rule["id"], 1.0 if ok else 0.0, comment))
    return results


def run_all(output: str) -> tuple[str, float, str]:
    """Weighted aggregate score in [0, 1], ready for langfuse.score(...)."""
    results = score(output)
    total = sum(r.get("weight", 1) for r, (_, v, _) in zip(RULES, results)) or 1
    value = sum(v * r.get("weight", 1) for r, (_, v, _) in zip(RULES, results)) / total
    failed = [rid for rid, v, _ in results if v == 0.0]
    comment = "all rules passed" if not failed else "failed: " + ", ".join(failed)
    return "rule_checks", round(value, 4), comment


if __name__ == "__main__":
    import sys
    sample = sys.stdin.read() if not sys.stdin.isatty() else ""
    name, value, comment = run_all(sample)
    print(f"{name}: {value:.2f} — {comment}")
`;
}

function emitJudgePrompt(a: SkillAnalysis): string {
  const criteria =
    a.qualityCriteria.length > 0
      ? a.qualityCriteria.map((c) => `- ${c}`).join("\n")
      : "- The answer fully accomplishes the skill's stated goal\n- The answer is accurate, clear and well-structured";
  const constraints =
    a.constraints.length > 0
      ? a.constraints.map((c) => `- ${c}`).join("\n")
      : "- (No hard constraints were detected in the skill.)";

  return `# LLM-as-a-Judge — ${a.displayName}

You are grading the output of an AI assistant that executed the skill **${a.skillName}**.

## Skill under test

> ${a.description || "(no description provided)"}

## Grading rubric (score each 1–5)

1. **Task completion** — does the output actually deliver what the skill promises?
2. **Instruction adherence** — does it follow the skill's workflow and hard rules?
3. **Quality criteria** — derived from the skill body:
${criteria}
4. **Format compliance** — expected format(s): ${a.formats.join(", ") || "free text"}.

## Hard constraints (violating any of these caps the total at 1)

${constraints}

## Input

\`\`\`
{{input}}
\`\`\`

## Output to grade

\`\`\`
{{output}}
\`\`\`

## Verdict format

Reply with **JSON only**:

\`\`\`json
{
  "task_completion": 1-5,
  "instruction_adherence": 1-5,
  "quality": 1-5,
  "format_compliance": 1-5,
  "constraint_violation": true | false,
  "reasoning": "2-3 sentences",
  "score": 0.0-1.0
}
\`\`\`

\`score\` = mean of the four 1–5 grades, normalised to 0–1; if \`constraint_violation\` is true, \`score\` must be ≤ 0.2.
`;
}

function emitJudgePy(a: SkillAnalysis): string {
  return `"""LLM-as-a-judge scorer for the "${a.skillName}" skill (Langfuse-compatible).

Generated by SkillFuse on ${DAY}.
Requires: pip install openai langfuse
Configure the judge model via env vars (see .env.example): works with any
OpenAI-compatible endpoint — your own model included.
"""

import json
import os
import re

from openai import OpenAI

JUDGE_PROMPT = open(os.path.join(os.path.dirname(__file__), "llm_judge_prompt.md"), encoding="utf-8").read()

client = OpenAI(
    base_url=os.environ.get("JUDGE_BASE_URL") or os.environ.get("OPENAI_BASE_URL") or None,
    api_key=os.environ.get("JUDGE_API_KEY") or os.environ.get("OPENAI_API_KEY"),
)
MODEL = os.environ.get("JUDGE_MODEL", "gpt-4o-mini")


def judge(input_text: str, output_text: str) -> tuple[str, float, str]:
    """Returns (name, value, comment) — value in [0, 1], ready for langfuse.score(...)."""
    prompt = JUDGE_PROMPT.replace("{{input}}", input_text or "").replace("{{output}}", output_text or "")
    resp = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )
    raw = resp.choices[0].message.content or ""
    m = re.search(r"\\{[\\s\\S]*\\}", raw)
    try:
        data = json.loads(m.group(0) if m else raw)
        value = max(0.0, min(1.0, float(data.get("score", 0))))
        return "llm_judge", round(value, 4), str(data.get("reasoning", ""))[:500]
    except Exception as exc:
        return "llm_judge", 0.0, f"judge parse error: {exc}; raw={raw[:200]}"


if __name__ == "__main__":
    import sys
    name, value, comment = judge(sys.argv[1] if len(sys.argv) > 1 else "", sys.stdin.read())
    print(f"{name}: {value:.2f} — {comment}")
`;
}

function emitLangfuseConfigPy(a: SkillAnalysis, datasetName: string, itemCount: number): string {
  return `"""One-shot Langfuse setup for the "${a.skillName}" skill.

Generated by SkillFuse on ${DAY}.

Usage:
    pip install langfuse openai
    cp .env.example .env   # fill in your keys
    python langfuse_config.py            # create dataset + upload items
    python langfuse_config.py --eval     # (skeleton) run your skill and score outputs

Dataset: ${datasetName} (${itemCount} items)
"""

import json
import os
import sys

from dotenv import load_dotenv  # pip install python-dotenv

load_dotenv()

from langfuse import Langfuse

langfuse = Langfuse(
    public_key=os.environ["LANGFUSE_PUBLIC_KEY"],
    secret_key=os.environ["LANGFUSE_SECRET_KEY"],
    host=os.environ.get("LANGFUSE_HOST", "https://cloud.langfuse.com"),
)

DATASET_NAME = "${datasetName}"
HERE = os.path.dirname(os.path.abspath(__file__))


def create_dataset() -> None:
    schema = json.load(open(os.path.join(HERE, "dataset_schema.json"), encoding="utf-8"))
    items = json.load(open(os.path.join(HERE, "dataset_items.json"), encoding="utf-8"))

    langfuse.create_dataset(
        name=DATASET_NAME,
        description=schema["description"],
        metadata=schema["metadata"],
    )
    for item in items:
        langfuse.create_dataset_item(
            dataset_name=DATASET_NAME,
            input=item["input"],
            expected_output=item.get("expectedOutput"),
            metadata=item.get("metadata", {}),
        )
    print(f"dataset '{DATASET_NAME}' created with {len(items)} items")


def run_evaluation(run_name: str = "skillfuse-run") -> None:
    """Skeleton: plug in *your* skill runner, then rule scorers + LLM judge score each output."""
    from rule_scorers import run_all as rule_score
    from llm_judge import judge

    dataset = langfuse.get_dataset(DATASET_NAME)
    for item in dataset.items:
        with item.observe(run_name=run_name) as trace_id:
            # TODO: replace with a real call that executes your skill on item.input
            output = "YOUR_SKILL_OUTPUT_HERE"

            name, value, comment = rule_score(output)
            langfuse.score(trace_id=trace_id, name=name, value=value, comment=comment)

            jname, jvalue, jcomment = judge(json.dumps(item.input, ensure_ascii=False), output)
            langfuse.score(trace_id=trace_id, name=jname, value=jvalue, comment=jcomment)

    langfuse.flush()
    print(f"evaluation run '{run_name}' finished — open Langfuse to inspect scores")


if __name__ == "__main__":
    if "--eval" in sys.argv:
        run_evaluation()
    else:
        create_dataset()
`;
}

function emitEnvExample(): string {
  return `# --- Langfuse (required) ---
LANGFUSE_PUBLIC_KEY=pk-lf-...
LANGFUSE_SECRET_KEY=sk-lf-...
LANGFUSE_HOST=https://cloud.langfuse.com

# --- Judge model (optional, any OpenAI-compatible endpoint / your own model) ---
JUDGE_BASE_URL=https://api.openai.com/v1
JUDGE_API_KEY=sk-...
JUDGE_MODEL=gpt-4o-mini
`;
}

function emitPackReadme(a: SkillAnalysis, rules: RuleCheck[], items: DatasetItem[]): string {
  return `# ${a.skillName}-eval — Langfuse evaluation pack

Generated by **SkillFuse** on ${DAY} from the skill's \`SKILL.md\`.

## What's inside

| File | Purpose |
| --- | --- |
| \`dataset_schema.json\` | Langfuse-compatible dataset definition (schema + metadata) |
| \`dataset_items.json\` | ${items.length} dataset items (happy-path, example-based, constraint-adversarial) |
| \`rule_scorers.py\` | ${rules.length} deterministic scorers, zero-dependency, weighted aggregate |
| \`rule_checks.json\` | the same rules as data — drives the SkillFuse in-browser test runner |
| \`llm_judge_prompt.md\` | LLM-as-a-judge rubric derived from the skill's quality criteria |
| \`llm_judge.py\` | judge scorer wired to any OpenAI-compatible endpoint |
| \`langfuse_config.py\` | one-shot dataset creation + evaluation-run skeleton |
| \`.env.example\` | environment template |

## Quick start

\`\`\`bash
pip install langfuse openai python-dotenv
cp .env.example .env   # fill in Langfuse keys (and judge model if used)
python langfuse_config.py
\`\`\`

## Notes

- Items marked \`"source": "skill-body"\` contain template \`expectedOutput\`s — replace them with
  concrete reference answers before relying on exact-match grading.
- Rule scorers are deterministic and free; the LLM judge is optional and only runs when
  \`JUDGE_API_KEY\` is set.
`;
}
